const ObjectId = require("mongodb").ObjectId;

module.exports = [
  {
    _id: ObjectId("63b1db13b2ade9465c9c5d0d"),
    name: "Roadster Elite",
    brand: "Argon 18",
    price: 1299.99,
    type: "Road",
    frame: "Carbon",
    fork: "XC",
    gears: "Derailleur gears",
    brakes: "Hydraulic Disc",
    wheels: "700c",
    tires: "Road tires",
    suspension: "Hardtail",
    weight: 7.5,
    available: true,
  },
  {
    _id: ObjectId("5f3d3b8aa2bcfd321e1c9d66"),
    name: "Mountain Monster",
    brand: "Bulls",
    price: 999.99,
    type: "Mountain",
    frame: "Aluminium",
    fork: "Trail",
    gears: "Derailleur gears",
    brakes: "Mechanical Disc",
    wheels: "27.5",
    tires: "Mountain bike tires",
    suspension: "Full",
    weight: 12.5,
    available: false,
  },
  {
    _id: ObjectId("63b1db3211c382e5701713d0"),
    name: "Commuter Classic",
    brand: "CUBE",
    price: 749.99,
    type: "Urban",
    frame: "Steel",
    fork: "Enduro",
    gears: "Internal gear hub",
    brakes: "Hydraulic Disc",
    wheels: "700c",
    tires: "Commuter tires",
    suspension: "Rigid",
    weight: 9.5,
    available: true,
  },
  {
    _id: ObjectId("63b1db40d3390ff95f72ac22"),
    name: "Roadster Elite",
    brand: "Argon 18",
    price: 1299.99,
    type: "Road",
    frame: "Carbon",
    fork: "XC",
    gears: "Derailleur gears",
    brakes: "Hydraulic Disc",
    wheels: "700c",
    tires: "Road tires",
    suspension: "Hardtail",
    weight: 7.5,
    available: false,
  },
  {
    _id: ObjectId("63b1db49e1b12a4e124903d5"),
    name: "Mountain Monster",
    brand: "Bulls",
    price: 999.99,
    type: "Mountain",
    frame: "Aluminium",
    fork: "Trail",
    gears: "Derailleur gears",
    brakes: "Mechanical Disc",
    wheels: "27.5",
    tires: "Mountain bike tires",
    suspension: "Full",
    weight: 12.5,
    available: true,
  },
  {
    _id: ObjectId("63b1db5591b219c3cfee9718"),
    name: "Commuter Classic",
    brand: "CUBE",
    price: 749.99,
    type: "Urban",
    frame: "Steel",
    fork: "Enduro",
    gears: "Internal gear hub",
    brakes: "Hydraulic Disc",
    wheels: "700c",
    tires: "Commuter tires",
    suspension: "Rigid",
    weight: 9.5,
    available: false,
  },
];
